twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    cartNav: "@App\\Cart\\CartService"

when@test:
  twig:
    strict_variables: true
